######################## default configuration ####################
baseURL = "https://www.tsumibon.tamari-b.com/"
defaultContentLanguage = "ja"
title = "つみぼん"
subtitle = "tamari bar"
theme = "tamaribar"
publishDir = "../docs"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "1"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-HD24SDZFXG" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
