############################# Japanese ############################
[ja]
languageName = "Ja"
title = "つみぼん"
subtitle = "tamari bar"
contentDir = "content/ja" # content/ja
weight = 1
########### footer content ##########
footer_menu_left = "Podcastより"
footer_menu_middle = "趣味の本たち"
footer_menu_right = "info & topics"
footer_content = "好きな本や気になる本を、ただただ積み重ねていくだけのサイト"
# copyright
copyright = "copyright @ tamari bar, all right reserved"
