#################### default parameters ################################
logo = "images/logo.png"
logo_width = "70px"
# OpenGraph / Twitter Card metadata
description = "好きな本、気になる本、興味のある本を集めたサイト。絵本、小説、漫画、実用書に加え、Podcastで紹介・引用された書籍も掲載しています。実用書は、何かを始める時に最初に読む本で、原理原則が書かれたものを中心にピックアップしています。"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# favicon
site_favicon = "images/logo_favicon.png"

# Type of pages to be rendered with a podcast view
CategoryType = "categories"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = false
label = ""
link = ""

# cookies
[cookies]
enable = true
expire_days = 365
content = "このサイトではcookieを使用しています。"
button = "I Accept"

########### Amazon ###########
[amazon]
associate_id = "tmr0b9-22"

########### social site ###########
# icons by FontAwesome
[[social]]
title = "twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/tamari_b"

[[social]]
title = "note"
icon = "fa-regular fa-sticky-note"
url = "https://note.com/tamari_b"

########### service link ###########
# icons by FontAwesome

## podcast1
[[podcast1]]
title = "apple podcast"
icon = "fab fa-apple"
url = "https://podcasts.apple.com/jp/podcast/%E8%B6%85%E7%9B%B8%E5%AF%BE%E6%80%A7%E7%90%86%E8%AB%96/id1567192930"

[[podcast1]]
title = "spotify"
icon = "fab fa-spotify"
url = "https://open.spotify.com/show/5xCiKGwndGU37pIuJTXpmD"

[[podcast1]]
title = "google podcast"
icon = "fab fa-google"
url = "https://podcasts.google.com/search/%E8%B6%85%E7%9B%B8%E5%AF%BE%E6%80%A7%E7%90%86%E8%AB%96"

## podcast2
[[podcast2]]
title = "apple podcast"
icon = "fab fa-apple"
url = "https://podcasts.apple.com/jp/podcast/%E3%82%86%E3%82%8B%E8%A8%80%E8%AA%9E%E5%AD%A6%E3%83%A9%E3%82%B8%E3%82%AA/id1550243290"

[[podcast2]]
title = "spotify"
icon = "fab fa-spotify"
url = "https://open.spotify.com/show/3nBZ3AgBAfSYdHbpJflIHZ"

[[podcast2]]
title = "google podcast"
icon = "fab fa-google"
url = "https://podcasts.google.com/search/%E3%82%86%E3%82%8B%E8%A8%80%E8%AA%9E%E5%AD%A6%E3%83%A9%E3%82%B8%E3%82%AA"

[[podcast2]]
title = "youtube"
icon = "fab fa-youtube"
url = "https://www.youtube.com/channel/UCmpkIzF3xFzhPez7gXOyhVg"

[[podcast2]]
title = "official"
icon = "fas fa-copyright"
url = "https://yurugengo.com/"

## podcast3
[[podcast3]]
title = "apple podcast"
icon = "fab fa-apple"
url = "https://podcasts.apple.com/jp/podcast/%E6%AD%B4%E5%8F%B2%E3%82%92%E9%9D%A2%E7%99%BD%E3%81%8F%E5%AD%A6%E3%81%B6%E3%82%B3%E3%83%86%E3%83%B3%E3%83%A9%E3%82%B8%E3%82%AA-coten-radio/id1450522865"

[[podcast3]]
title = "spotify"
icon = "fab fa-spotify"
url = "https://open.spotify.com/show/3qiAapMhh8UgWVfDWTSq2f?si=3f260c76a0db431f&nd=1"

[[podcast3]]
title = "google podcast"
icon = "fab fa-google"
url = "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy84YzIwODhjL3BvZGNhc3QvcnNz"

[[podcast3]]
title = "youtube"
icon = "fab fa-youtube"
url = "https://www.youtube.com/c/cotenradio"

[[podcast3]]
title = "official"
icon = "fas fa-copyright"
url = "https://cotenradio.fm/"
